apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools-display
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  ui:
    input:
      variables:
        project_id:
          name: project_id
          title: Project Id
          invisible: true
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        source_image:
          name: source_image
          title: Image version
          enumValueLabels:
            - label: image-mikopbx-2024-1-114-x86-64-v5
              value: projects/mikopbx-public/global/images/image-mikopbx-2024-1-114-x86-64-v5
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
        machine_type:
          name: machine_type
          title: Machine type
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone
            gceMachineType:
              minCpu: 1
              minRamGb: 1
        boot_disk_type:
          name: boot_disk_type
          title: Boot disk type
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone
        boot_disk_size:
          name: boot_disk_size
          title: Boot disk size in GB
          max: 10000
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
            gceDiskSize:
              diskTypeVariable: boot_disk_type
        storage_disk_type:
          name: storage_disk_type
          title: Storage disk type
          section: data_storage
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone      
        storage_disk_size:
          name: storage_disk_size
          title: Data storage disk size in GBs
          tooltip: 'Specify the disk size for additional data storage in gigabytes. This disk is separate from the boot disk and is used solely for storing data. <a href="https://cloud.google.com/compute/docs/disks/">Learn more</a>'
          section: data_storage
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
            gceDiskSize:
              diskTypeVariable: storage_disk_type
        zone:
          name: zone
          title: Zone
          xGoogleProperty:
            type: ET_GCE_ZONE
        networks:
          name: networks
          title: Network name
          minItems: 1
          maxItems: 1
          section: networking
          xGoogleProperty:
            type: ET_GCE_NETWORK
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
        sub_networks:
          name: subnetworks
          title: Subnetwork name
          minItems: 1
          maxItems: 1
          section: networking
          xGoogleProperty:
            type: ET_GCE_SUBNETWORK
            zoneProperty: zone
            gceSubnetwork:
              networkVariable: networks
        external_ips:
          name: external_ips
          title: External IP
          tooltip: 'An external IP address associated with this instance. Selecting "None" will result in the instance having no external internet access. <a href="https://cloud.google.com/compute/docs/configure-instance-ip-addresses">Learn more</a>'
          minItems: 1
          maxItems: 1
          section: networking
          xGoogleProperty:
            type: ET_GCE_EXTERNAL_IP
            gceExternalIp:
              networkVariable: networks
              notConfigurable: false
              allowStaticIps: true
        enable_tcp_443:
          name: enable_tcp_443
          title: Allow HTTPS traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        tcp_443_source_ranges:
          name: tcp_443_source_ranges
          title: Source IP ranges for HTTPS traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_443
        enable_tcp_5060:
          name: enable_tcp_5060
          title: Allow TCP port 5060 SIP traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        tcp_5060_source_ranges:
          name: tcp_5060_source_ranges
          title: Source IP ranges for TCP port 5060 SIP traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_5060
        enable_udp_5060:
          name: enable_udp_5060
          title: Allow UDP port 5060 SIP traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        udp_5060_source_ranges:
          name: udp_5060_source_ranges
          title: Source IP ranges for UDP port 5060 SIP traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_udp_5060
        enable_tcp_5061:
          name: enable_tcp_5061
          title: Allow TCP port 5061 SIP_TLS traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        tcp_5061_source_ranges:
          name: tcp_5061_source_ranges
          title: Source IP ranges for TCP port 5061 SIP_TLS traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_5061
        enable_udp_10000_10800:
          name: enable_udp_10000_10800
          title: Allow UDP ports 10000-10800 RTP traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        udp_10000_10800_source_ranges:
          name: udp_10000_10800_source_ranges
          title: Source IP ranges for UDP ports 10000-10800 RTP traffic
          tooltip: 'Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0, 192.169.0.2/24'
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_udp_10000_10800      
        ip_forward:
          name: ip_forward
          title: IP forwarding
          tooltip: 'Forwarding allows the instance to help route packets. <a href="https://cloud.google.com/compute/docs/networking#canipforward">Learn more</a>'
          section: networking
          level: 1
          xGoogleProperty:
            type: ET_GCE_IP_FORWARDING
            gceIpForwarding:
              networkVariable: networks
              notConfigurable: false
      sections:
        - name: boot_disk
          title: Boot Disk
          tooltip: Each instance requires a disk to boot from.
        - name: data_storage
          title: Data Storage
          tooltip: 'Configure settings related to additional data storage disks.'  
        - name: networking
          title: Networking
    runtime:
      suggestedActions:
        - heading: After launching instructions
          description: |
            After launching the instance, you need to connect to the serial console, wait for the system to fully boot and complete the provisioning, and then retrieve the credentials for logging into the web interface and SSH console. Alternatively, you can wait 5 minutes after the instance first starts, open a browser, and go to https://[External IP address]. Use admin as the login and the unique identifier of the instance as the password.