apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Marketplace Terraform Module for MikoPBX
    version: 2024.1.114
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: x86_64 GNU/Linux
            version: "6.6.1"
      - software:
          - title: Asterisk
            version: "20.7.0"
          - title: PHP
            version: "7.4"
          - title: Phalcon
            version: "4.1.0"
          - title: Redis
            version: "6.2.1"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/mikopbx-public/global/images/image-mikopbx-2024-1-114-x86-64-v5
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        defaultValue: us-east1-b
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-balanced
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: integer
        defaultValue: 10
      - name: storage_disk_type
        description: Storage disk type.
        varType: string
        defaultValue: pd-balanced  
      - name: storage_disk_size
        description: The size of the storage disk in GBs
        varType: integer
        defaultValue: 50    
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: e2-small
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue:
          - default
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: []
      - name: external_ips
        description: The external IPs assigned to the VM for public access.
        varType: list(string)
        defaultValue:
          - EPHEMERAL
      - name: enable_tcp_443_80
        description: Allow HTTP traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_443_80_source_ranges
        description: Source IP ranges for HTTP traffic
        varType: string
        defaultValue: ""
      - name: enable_tcp_5060
        description: Allow TCP port 5060 SIP traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_5060_source_ranges
        description: Source IP ranges for TCP port 5060 SIP traffic
        varType: string
        defaultValue: ""
      - name: enable_udp_5060
        description: Allow UDP port 5060 SIP traffic from the Internet
        varType: bool
        defaultValue: true
      - name: udp_5060_source_ranges
        description: Source IP ranges for UDP port 5060 SIP traffic
        varType: string
        defaultValue: ""
      - name: enable_tcp_5061
        description: Allow TCP port 5061 SIP TLS traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_5061_source_ranges
        description: Source IP ranges for TCP port 5061 SIP TLS traffic
        varType: string
        defaultValue: ""
      - name: enable_udp_10000_10800
        description: Allow UDP ports 10000-10800 traffic from the Internet
        varType: bool
        defaultValue: true
      - name: udp_10000_10800_source_ranges
        description: Source IP ranges for UDP ports 10000-10800 RTP traffic
        varType: string
        defaultValue: ""
      - name: ip_forward
        description: Whether to allow sending and receiving of packets with non-matching source or destination IPs.
        varType: bool
        defaultValue: false
      - name: enable_cloud_logging
        description: Enables Cloud Logging.
        varType: bool
        defaultValue: true
      - name: enable_cloud_monitoring
        description: Enables Cloud Monitoring.
        varType: bool
        defaultValue: true
    outputs:
      - name: admin_url
        description: URL of the web console (please wait 3 minutes after creation before accessing)
      - name: login_hint
        description: Login hint for the web console
      - name: instance_machine_type
        description: Machine type for the compute instance.  
      - name: instance_nat_ip
        description: External IP of the compute instance.
      - name: instance_network
        description: Self-link for the network of the compute instance.
      - name: instance_self_link
        description: Self-link for the compute instance.
      - name: instance_zone
        description: Zone for the compute instance.